### ISSUE TITLE
New Installation problem - blank page on login

### ISSUE THREAD

**Issue by pgfowler1** [ChurchInfo/ChurchInfoWeb#3]
Hi,  I have just installed this fork but get this error in the source of the password change page and a blank screen under the menu 

<ul class="dropdown-menu">
                            Cannot execute query.<p>SELECT name, ismenu, parent, content, uri, statustext, session_var, session_var_in_text, session_var_in_uri, url_parm_name, security_grp, icon FROM menuconfig_mcf WHERE parent = 'admin' AND active=1  AND (security_grp = 'bALL' OR security_grp = 'bAdmin' OR security_grp = 'bAddRecords' OR security_grp = 'bEditRecords' OR security_grp = 'bDeleteRecords' OR security_grp = 'bMenuOptions' OR security_grp = 'bManageGroups' OR security_grp = 'bFinance' OR security_grp = 'bNotes' OR security_grp = 'bCommunication' OR security_grp = 'bCanvasser' OR security_grp = 'bCreateDirectory' OR security_grp = 'bExportCSV') ORDER BY sortorder<p>Unknown column 'icon' in 'field list'

**Comment by gdawoud** [comment]
Hi Sorry I have not worked on a full deployment script yet... maybe your post will make me get on it this weekend....

That said... Please run the SQL below it will drop this table and recreate it with the correct data...

**Comment by pgfowler1** [comment]
Cheers, that fixed it.  Like the interface btw.
